#
# Copyright (C) 2024 RTA SERVER
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Base64
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-base64
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature