#
# Copyright (C) 2024 RTA SERVER
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=NetMonitor
LUCI_DEPENDS:=+netdata
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-netmonitor
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
