name: Auto compile with OpenWrt SDK

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      upload-artifacts:
        description: "Upload compiled image to Artifacts only"
        required: false
        default: false
        type: boolean
      upload-prerelease:
        description: "Upload as pre-release"
        required: false
        default: false
        type: boolean

env:
  TZ: Asia/Jakarta

jobs:
  job_build_rta:
    name: Build RTA (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev git-core subversion gettext unzip zlib1g-dev file perl libssl-dev wget

      - name: Download and setup OpenWrt SDK
        env:
          SDK_URL: https://archive.openwrt.org/releases/21.02.5/targets/x86/64/openwrt-sdk-21.02.5-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        run: |
          wget $SDK_URL
          tar -xJf *.tar.xz --strip-components=1 -C ./sdk
          cd sdk
          echo "src-git base https://github.com/openwrt/openwrt.git;openwrt-21.02" > feeds.conf
          echo "src-git-full packages https://github.com/openwrt/packages.git;openwrt-21.02" >> feeds.conf
          echo "src-git-full luci https://git.openwrt.org/project/luci.git;openwrt-21.02" >> feeds.conf
          echo "src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-21.02"  >> feeds.conf
          git clone https://github.com/${{ github.repository }}.git package/downloads
          ./scripts/feeds update -a
          packages=(
            "luci-app-base64"
            "luci-app-libernet"
            "luci-app-libernet-bin"
            "luci-app-libernet-plus"
            "luci-app-mikhmon"
            "luci-app-mikhmon4"
            "luci-app-netmonitor"
            "luci-app-wegare"
            "luci-app-xderm"
            "luci-app-xderm-bin"
            "luci-app-xderm-limit"
          )
          for pkg in "${packages[@]}"
          do
            ./scripts/feeds install -d n "$pkg"
          done

      - name: Configure and compile RTA (main)
        run: |
          cd sdk
          make defconfig
          make package/*/compile
          mv bin/packages/x86_64/base/* ../
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y.%m.%d-%H:%M:%S')" >> $GITHUB_ENV

      - name: Upload All Firmware to Artifacts
        if: github.event.inputs.upload-artifacts == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt RTA Packages
          path: ${{ env.FIRMWARE }}/base/*.ipk

      - name: Upload Firmware to Release
        uses: svenstaro/upload-release-action@v2
        if: github.event.inputs.upload-artifacts == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ env.FIRMWARE }}/base/*.ipk
          asset_name: ${{ github.event.repository.name }}-${{ github.sha }}
          tag: latest
          release_name: OpenWrt RTA Packages
          overwrite: true
          prerelease: ${{ inputs.upload-prerelease }}
          body: |
            Build date: ${{ env.DATETIME }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0