name: Create Rooter2305 Patch

on:
  workflow_dispatch:
  schedule:
    - cron: "00 19 * * *" # 02:00 GMT+7

env:
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone Repo
      run: git clone https://github.com/ofmodemsandmen/ROOterSource2305.git openwrt

    - name: Create Rooter2305 Patch
      run: |
        echo "DATETIME=$(date +'%Y.%m.%d-%H:%M:%S')" >> $GITHUB_ENV
        cp -rf openwrt/package* ./package
        cp -rf openwrt/package/rooter-builds/0protocols/luci-proto-3x/* ./luci-proto-3x
        cp -rf openwrt/package/rooter-builds/0protocols/luci-proto-mbim/* ./luci-proto-mbim
        cp -rf openwrt/package/rooter-extra/ext-netselect/* ./ext-netselect
        cp -rf openwrt/package/rooter-extra/ext-selectisp/* ./ext-selectisp
        cp -rf openwrt/package/rooter-extra/ext-simpin/* ./ext-simpin
        cp -rf openwrt/package/rooter-extra/ext-simplegps/* ./ext-simplegps
        cp -rf openwrt/package/rooter-extra/netrestart/* ./netrestart
        cp -rf openwrt/package/rooter/0basicapps/ext-command/* ./ext-command
        cp -rf openwrt/package/rooter/0basicapps/ext-extra/* ./ext-extra
        cp -rf openwrt/package/rooter/0basicsupport/ext-buttons/* ./ext-buttons
        cp -rf openwrt/package/rooter/0basicsupport/ext-sms/* ./ext-sms
        cp -rf openwrt/package/rooter/0drivers/rmbim/* ./rmbim
        cp -rf openwrt/package/rooter/0drivers/rqmi/* ./rqmi
        cp -rf openwrt/package/rooter/ext-rooter-basic/* ./ext-rooter-basic
        rm -rf openwrt

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_options: '--no-verify --signoff'
        push_options: '--force'
        commit_message: "🎉 Sync: ${{ env.DATETIME }}"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
